AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to automatically shut down EC2 instances at midnight'

Resources:
  StopEC2InstancesFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: 'index.lambda_handler'
      Runtime: 'python3.8'
      Timeout: 60
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import boto3
          import logging
          import os
          from datetime import datetime

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          ec2 = boto3.client('ec2')

          def lambda_handler(event, context):
              logger.info('Stopping EC2 instances at midnight...')

              # Get all running instances
              response = ec2.describe_instances(Filters=[{'Name': 'instance-state-name', 'Values': ['running']}])
              instance_ids = [instance['InstanceId'] for reservation in response['Reservations'] for instance in reservation['Instances']]

              # Stop each running instance
              for instance_id in instance_ids:
                  logger.info(f'Stopping instance: {instance_id}')
                  ec2.stop_instances(InstanceIds=[instance_id])

              logger.info('EC2 instances stopped successfully.')

  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 'lambda.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'LambdaExecutionPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ec2:DescribeInstances'
                  - 'ec2:StopInstances'
                Resource: '*'

  MidnightShutdownRule:
    Type: 'AWS::Events::Rule'
    Properties:
      ScheduleExpression: 'cron(0 0 * * ? *)'  # Trigger at midnight UTC
      State: 'ENABLED'
      Targets:
        - Arn: !GetAtt StopEC2InstancesFunction.Arn
          Id: 'StopEC2InstancesFunction'
